SET DN_FOLDER=%1
SET OUTPUT_FOLDER=%2

quickbms -f "\*.dnt" script.txt %DN_FOLDER%\Resource00.pak %OUTPUT_FOLDER%
quickbms -f "\*.dnt" script.txt %DN_FOLDER%\Resource01.pak %OUTPUT_FOLDER%
quickbms -f "\*.dnt" script.txt %DN_FOLDER%\Resource02.pak %OUTPUT_FOLDER%
quickbms -f "\*.dnt" script.txt %DN_FOLDER%\Resource03.pak %OUTPUT_FOLDER%
quickbms -f "\*.dnt" script.txt %DN_FOLDER%\Resource04.pak %OUTPUT_FOLDER%
quickbms -f "\*.dnt" script.txt %DN_FOLDER%\Resource05.pak %OUTPUT_FOLDER%
quickbms -f "\*.dnt" script.txt %DN_FOLDER%\Resource06.pak %OUTPUT_FOLDER%
quickbms -f "\*.dnt" script.txt %DN_FOLDER%\Resource07.pak %OUTPUT_FOLDER%
quickbms -f "\*.dnt" script.txt %DN_FOLDER%\Resource08.pak %OUTPUT_FOLDER%
quickbms -f "\*.dnt" script.txt %DN_FOLDER%\Resource09.pak %OUTPUT_FOLDER%
quickbms -f "\*.dnt" script.txt %DN_FOLDER%\Resource10.pak %OUTPUT_FOLDER%
quickbms -f "\*.dnt" script.txt %DN_FOLDER%\Resource11.pak %OUTPUT_FOLDER%
quickbms -f "\*.dnt" script.txt %DN_FOLDER%\Resource12.pak %OUTPUT_FOLDER%
quickbms -f "\*.dnt" script.txt %DN_FOLDER%\Resource13.pak %OUTPUT_FOLDER%
quickbms -f "\*.dnt" script.txt %DN_FOLDER%\Resource14.pak %OUTPUT_FOLDER%
quickbms -f "\*.dnt" script.txt %DN_FOLDER%\Resource15.pak %OUTPUT_FOLDER%
quickbms -f "\*.dnt" script.txt %DN_FOLDER%\Resource16.pak %OUTPUT_FOLDER%
quickbms -f "\*.dnt" script.txt %DN_FOLDER%\Resource17.pak %OUTPUT_FOLDER%
quickbms -f "\*.dnt" script.txt %DN_FOLDER%\Resource18.pak %OUTPUT_FOLDER%
quickbms -f "\*.dnt" script.txt %DN_FOLDER%\Resource19.pak %OUTPUT_FOLDER%
quickbms -f "\*.dnt" script.txt %DN_FOLDER%\Resource20.pak %OUTPUT_FOLDER%
quickbms -f "\*.dnt" script.txt %DN_FOLDER%\Resource21.pak %OUTPUT_FOLDER%
quickbms -f "\*.dnt" script.txt %DN_FOLDER%\Resource22.pak %OUTPUT_FOLDER%
quickbms -f "\*.dnt" script.txt %DN_FOLDER%\Resource23.pak %OUTPUT_FOLDER%

quickbms -f "\*uistring.xml" script.txt %DN_FOLDER%\Resource00.pak %OUTPUT_FOLDER%
quickbms -f "\*uistring.xml" script.txt %DN_FOLDER%\Resource01.pak %OUTPUT_FOLDER%
quickbms -f "\*uistring.xml" script.txt %DN_FOLDER%\Resource02.pak %OUTPUT_FOLDER%
quickbms -f "\*uistring.xml" script.txt %DN_FOLDER%\Resource03.pak %OUTPUT_FOLDER%
quickbms -f "\*uistring.xml" script.txt %DN_FOLDER%\Resource04.pak %OUTPUT_FOLDER%
quickbms -f "\*uistring.xml" script.txt %DN_FOLDER%\Resource05.pak %OUTPUT_FOLDER%
quickbms -f "\*uistring.xml" script.txt %DN_FOLDER%\Resource06.pak %OUTPUT_FOLDER%
quickbms -f "\*uistring.xml" script.txt %DN_FOLDER%\Resource07.pak %OUTPUT_FOLDER%
quickbms -f "\*uistring.xml" script.txt %DN_FOLDER%\Resource08.pak %OUTPUT_FOLDER%
quickbms -f "\*uistring.xml" script.txt %DN_FOLDER%\Resource09.pak %OUTPUT_FOLDER%
quickbms -f "\*uistring.xml" script.txt %DN_FOLDER%\Resource10.pak %OUTPUT_FOLDER%
quickbms -f "\*uistring.xml" script.txt %DN_FOLDER%\Resource11.pak %OUTPUT_FOLDER%
quickbms -f "\*uistring.xml" script.txt %DN_FOLDER%\Resource12.pak %OUTPUT_FOLDER%
quickbms -f "\*uistring.xml" script.txt %DN_FOLDER%\Resource13.pak %OUTPUT_FOLDER%
quickbms -f "\*uistring.xml" script.txt %DN_FOLDER%\Resource14.pak %OUTPUT_FOLDER%
quickbms -f "\*uistring.xml" script.txt %DN_FOLDER%\Resource15.pak %OUTPUT_FOLDER%
quickbms -f "\*uistring.xml" script.txt %DN_FOLDER%\Resource16.pak %OUTPUT_FOLDER%
quickbms -f "\*uistring.xml" script.txt %DN_FOLDER%\Resource17.pak %OUTPUT_FOLDER%
quickbms -f "\*uistring.xml" script.txt %DN_FOLDER%\Resource18.pak %OUTPUT_FOLDER%
quickbms -f "\*uistring.xml" script.txt %DN_FOLDER%\Resource19.pak %OUTPUT_FOLDER%
quickbms -f "\*uistring.xml" script.txt %DN_FOLDER%\Resource20.pak %OUTPUT_FOLDER%
quickbms -f "\*uistring.xml" script.txt %DN_FOLDER%\Resource21.pak %OUTPUT_FOLDER%
quickbms -f "\*uistring.xml" script.txt %DN_FOLDER%\Resource22.pak %OUTPUT_FOLDER%
quickbms -f "\*uistring.xml" script.txt %DN_FOLDER%\Resource23.pak %OUTPUT_FOLDER%

quickbms -f "\*mainbar\*.dds" script.txt %DN_FOLDER%\Resource00.pak %OUTPUT_FOLDER%
quickbms -f "\*mainbar\*.dds" script.txt %DN_FOLDER%\Resource01.pak %OUTPUT_FOLDER%
quickbms -f "\*mainbar\*.dds" script.txt %DN_FOLDER%\Resource02.pak %OUTPUT_FOLDER%
quickbms -f "\*mainbar\*.dds" script.txt %DN_FOLDER%\Resource03.pak %OUTPUT_FOLDER%
quickbms -f "\*mainbar\*.dds" script.txt %DN_FOLDER%\Resource04.pak %OUTPUT_FOLDER%
quickbms -f "\*mainbar\*.dds" script.txt %DN_FOLDER%\Resource05.pak %OUTPUT_FOLDER%
quickbms -f "\*mainbar\*.dds" script.txt %DN_FOLDER%\Resource06.pak %OUTPUT_FOLDER%
quickbms -f "\*mainbar\*.dds" script.txt %DN_FOLDER%\Resource07.pak %OUTPUT_FOLDER%
quickbms -f "\*mainbar\*.dds" script.txt %DN_FOLDER%\Resource08.pak %OUTPUT_FOLDER%
quickbms -f "\*mainbar\*.dds" script.txt %DN_FOLDER%\Resource09.pak %OUTPUT_FOLDER%
quickbms -f "\*mainbar\*.dds" script.txt %DN_FOLDER%\Resource10.pak %OUTPUT_FOLDER%
quickbms -f "\*mainbar\*.dds" script.txt %DN_FOLDER%\Resource11.pak %OUTPUT_FOLDER%
quickbms -f "\*mainbar\*.dds" script.txt %DN_FOLDER%\Resource12.pak %OUTPUT_FOLDER%
quickbms -f "\*mainbar\*.dds" script.txt %DN_FOLDER%\Resource13.pak %OUTPUT_FOLDER%
quickbms -f "\*mainbar\*.dds" script.txt %DN_FOLDER%\Resource14.pak %OUTPUT_FOLDER%
quickbms -f "\*mainbar\*.dds" script.txt %DN_FOLDER%\Resource15.pak %OUTPUT_FOLDER%
quickbms -f "\*mainbar\*.dds" script.txt %DN_FOLDER%\Resource16.pak %OUTPUT_FOLDER%
quickbms -f "\*mainbar\*.dds" script.txt %DN_FOLDER%\Resource17.pak %OUTPUT_FOLDER%
quickbms -f "\*mainbar\*.dds" script.txt %DN_FOLDER%\Resource18.pak %OUTPUT_FOLDER%
quickbms -f "\*mainbar\*.dds" script.txt %DN_FOLDER%\Resource19.pak %OUTPUT_FOLDER%
quickbms -f "\*mainbar\*.dds" script.txt %DN_FOLDER%\Resource20.pak %OUTPUT_FOLDER%
quickbms -f "\*mainbar\*.dds" script.txt %DN_FOLDER%\Resource21.pak %OUTPUT_FOLDER%
quickbms -f "\*mainbar\*.dds" script.txt %DN_FOLDER%\Resource22.pak %OUTPUT_FOLDER%
quickbms -f "\*mainbar\*.dds" script.txt %DN_FOLDER%\Resource23.pak %OUTPUT_FOLDER%
